//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("projet_mozambique.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;avez pas accès à cette section..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le contenu du message ne peut être vide..
        /// </summary>
        public static string contenuObligatoire {
            get {
                return ResourceManager.GetString("contenuObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La description ne peut être vide..
        /// </summary>
        public static string descriptionVide {
            get {
                return ResourceManager.GetString("descriptionVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La liste des destinataires ne peut être vide..
        /// </summary>
        public static string destObligatoire {
            get {
                return ResourceManager.GetString("destObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ {0} est obligatoire..
        /// </summary>
        public static string fieldRequired {
            get {
                return ResourceManager.GetString("fieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ {0} doit comprendre au moins {2} caractères..
        /// </summary>
        public static string fieldStringLength {
            get {
                return ResourceManager.GetString("fieldStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le message bien été envoyé..
        /// </summary>
        public static string messageEnvoye {
            get {
                return ResourceManager.GetString("messageEnvoye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le message n&apos;a pu être envoyé, une erreur est survenue..
        /// </summary>
        public static string messagePasEnvoye {
            get {
                return ResourceManager.GetString("messagePasEnvoye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les messages ont bien été supprimés..
        /// </summary>
        public static string messagesSupprimes {
            get {
                return ResourceManager.GetString("messagesSupprimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le message a bien été supprimé..
        /// </summary>
        public static string messageSupprime {
            get {
                return ResourceManager.GetString("messageSupprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nouveau mot de passe et la confirmation ne correspondent pas..
        /// </summary>
        public static string NewPasswordMatch {
            get {
                return ResourceManager.GetString("NewPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce champ ne peut pas être modifié..
        /// </summary>
        public static string nonEditable {
            get {
                return ResourceManager.GetString("nonEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La nouvelle a bien été ajoutée..
        /// </summary>
        public static string nouvelleAjoutee {
            get {
                return ResourceManager.GetString("nouvelleAjoutee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La nouvelle a bien été modifiée..
        /// </summary>
        public static string nouvelleModifiee {
            get {
                return ResourceManager.GetString("nouvelleModifiee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La nouvelle n&apos;a pu être ajoutée..
        /// </summary>
        public static string nouvellePasAjoutee {
            get {
                return ResourceManager.GetString("nouvellePasAjoutee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La nouvelle a bien été supprimée..
        /// </summary>
        public static string nouvelleSupprimee {
            get {
                return ResourceManager.GetString("nouvelleSupprimee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un courriel vous a été envoyé pour confirmer la réinitialisation de votre mot de passe..
        /// </summary>
        public static string PasswordResetConfirm {
            get {
                return ResourceManager.GetString("PasswordResetConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La pièce jointe dépasse la taille limite qui est de {0} MB..
        /// </summary>
        public static string pieceTropLourde {
            get {
                return ResourceManager.GetString("pieceTropLourde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le sujet du message ne peut être vide..
        /// </summary>
        public static string sujetObligatoire {
            get {
                return ResourceManager.GetString("sujetObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le titre ne peut être vide..
        /// </summary>
        public static string titreVide {
            get {
                return ResourceManager.GetString("titreVide", resourceCulture);
            }
        }
    }
}
