//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_mozambique.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTENU
    {
        public int ID { get; set; }
        public string PAGE { get; set; }
        public string TITRE { get; set; }
        public string TITRE_TRAD { get; set; }
        public string CONTENU1 { get; set; }
        public string CONTENU_TRAD { get; set; }
        public string URLIMAGE { get; set; }
    }
}
