//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_mozambique.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESTINATAIREMESSAGE
    {
        public int IDMESSAGE { get; set; }
        public int IDUTILISATEUR { get; set; }
        public bool SUPPRIME { get; set; }
        public bool SUPPRIMEDEFINITIF { get; set; }
    
        public virtual MESSAGEPRIVE MESSAGEPRIVE { get; set; }
        public virtual UTILISATEUR UTILISATEUR { get; set; }
    }
}
