//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_mozambique.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECOLE
    {
        public ECOLE()
        {
            this.UTILISATEUR = new HashSet<UTILISATEUR>();
            this.SECTEUR = new HashSet<SECTEUR>();
        }
    
        public int ID { get; set; }
        public string NOM { get; set; }
        public string PROVINCE { get; set; }
    
        public virtual ICollection<UTILISATEUR> UTILISATEUR { get; set; }
        public virtual ICollection<SECTEUR> SECTEUR { get; set; }
    }
}
