//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_mozambique.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGEPRIVE
    {
        public MESSAGEPRIVE()
        {
            this.DESTINATAIREMESSAGE = new HashSet<DESTINATAIREMESSAGE>();
            this.PIECEJOINTE = new HashSet<PIECEJOINTE>();
        }
    
        public int ID { get; set; }
        public int IDEXPEDITEUR { get; set; }
        public string SUJET { get; set; }
        public string CONTENU { get; set; }
        public System.DateTime DATEENVOI { get; set; }
        public bool SUPPRIME { get; set; }
        public bool SUPPRIMEDEFINITIF { get; set; }
    
        public virtual ICollection<DESTINATAIREMESSAGE> DESTINATAIREMESSAGE { get; set; }
        public virtual UTILISATEUR UTILISATEUR { get; set; }
        public virtual ICollection<PIECEJOINTE> PIECEJOINTE { get; set; }
    }
}
