//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_mozambique.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOUVELLE
    {
        public int ID { get; set; }
        public string TITRE { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime DATEPUBLICATION { get; set; }
        public string TITRETRAD { get; set; }
        public string DESCRIPTIONTRAD { get; set; }
    }
}
