//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_mozambique.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIECEJOINTE
    {
        public int ID { get; set; }
        public int IDMESSAGE { get; set; }
        public byte[] PIECESERIALISEE { get; set; }
        public string TAILLEPIECE { get; set; }
        public string NOMPIECE { get; set; }
    
        public virtual MESSAGEPRIVE MESSAGEPRIVE { get; set; }
    }
}
