//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_mozambique.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECTEUR
    {
        public SECTEUR()
        {
            this.FORUM = new HashSet<FORUM>();
            this.PUBLICATION = new HashSet<PUBLICATION>();
            this.SONDAGE = new HashSet<SONDAGE>();
            this.UTILISATEURSECTEUR = new HashSet<UTILISATEURSECTEUR>();
            this.ECOLE = new HashSet<ECOLE>();
            this.EVENEMENT = new HashSet<EVENEMENT>();
        }
    
        public int ID { get; set; }
        public string NOM { get; set; }
        public string TITREACCUEIL { get; set; }
        public string TEXTEACCUEIL { get; set; }
        public string URLIMAGEACCUEIL { get; set; }
    
        public virtual ICollection<FORUM> FORUM { get; set; }
        public virtual ICollection<PUBLICATION> PUBLICATION { get; set; }
        public virtual ICollection<SONDAGE> SONDAGE { get; set; }
        public virtual ICollection<UTILISATEURSECTEUR> UTILISATEURSECTEUR { get; set; }
        public virtual ICollection<ECOLE> ECOLE { get; set; }
        public virtual ICollection<EVENEMENT> EVENEMENT { get; set; }
    }
}
