//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_mozambique.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SONDAGE
    {
        public SONDAGE()
        {
            this.CHOIXSONDAGE = new HashSet<CHOIXSONDAGE>();
        }
    
        public int ID { get; set; }
        public string NOM { get; set; }
        public string QUESTION { get; set; }
        public System.DateTime DATEDEBUT { get; set; }
        public System.DateTime DATEFIN { get; set; }
        public int IDCREATEUR { get; set; }
        public int IDSECTEUR { get; set; }
        public string NOMTRAD { get; set; }
        public string QUESTIONTRAD { get; set; }
    
        public virtual ICollection<CHOIXSONDAGE> CHOIXSONDAGE { get; set; }
        public virtual SECTEUR SECTEUR { get; set; }
        public virtual UTILISATEUR UTILISATEUR { get; set; }
    }
}
