//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_mozambique.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTILISATEURSECTEUR
    {
        public int IDUTILISATEUR { get; set; }
        public int IDSECTEUR { get; set; }
        public System.DateTime DEBUTACCES { get; set; }
        public System.DateTime FINACCES { get; set; }
    
        public virtual SECTEUR SECTEUR { get; set; }
        public virtual UTILISATEUR UTILISATEUR { get; set; }
    }
}
