//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_mozambique.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTILISATEUR
    {
        public UTILISATEUR()
        {
            this.DESTINATAIREMESSAGE = new HashSet<DESTINATAIREMESSAGE>();
            this.EVENEMENT = new HashSet<EVENEMENT>();
            this.MESSAGEFORUM = new HashSet<MESSAGEFORUM>();
            this.MESSAGEPRIVE = new HashSet<MESSAGEPRIVE>();
            this.PUBLICATION = new HashSet<PUBLICATION>();
            this.SONDAGE = new HashSet<SONDAGE>();
            this.UTILISATEURSECTEUR = new HashSet<UTILISATEURSECTEUR>();
            this.CHOIXSONDAGE = new HashSet<CHOIXSONDAGE>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int ID { get; set; }
        public string NOMUTIL { get; set; }
        public string COURRIEL { get; set; }
        public string PRENOM { get; set; }
        public string NOM { get; set; }
        public string ADRESSE { get; set; }
        public string VILLE { get; set; }
        public System.DateTime DATENAISSANCE { get; set; }
        public Nullable<System.DateTime> DERNIERECONNEXION { get; set; }
        public string LANGUE { get; set; }
        public int IDECOLE { get; set; }
        public bool ACTIF { get; set; }
    
        public virtual ICollection<DESTINATAIREMESSAGE> DESTINATAIREMESSAGE { get; set; }
        public virtual ECOLE ECOLE { get; set; }
        public virtual ICollection<EVENEMENT> EVENEMENT { get; set; }
        public virtual ICollection<MESSAGEFORUM> MESSAGEFORUM { get; set; }
        public virtual ICollection<MESSAGEPRIVE> MESSAGEPRIVE { get; set; }
        public virtual ICollection<PUBLICATION> PUBLICATION { get; set; }
        public virtual ICollection<SONDAGE> SONDAGE { get; set; }
        public virtual ICollection<UTILISATEURSECTEUR> UTILISATEURSECTEUR { get; set; }
        public virtual ICollection<CHOIXSONDAGE> CHOIXSONDAGE { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
