//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34003
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez le projet Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Admin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Admin() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Admin", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une nouvelle.
        /// </summary>
        internal static string ajouterNouvelle {
            get {
                return ResourceManager.GetString("ajouterNouvelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création d&apos;un nouvel utilisateur.
        /// </summary>
        internal static string ajoutUtilisateur {
            get {
                return ResourceManager.GetString("ajoutUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun résultat.
        /// </summary>
        internal static string aucunResultat {
            get {
                return ResourceManager.GetString("aucunResultat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image actuelle.
        /// </summary>
        internal static string CurrentImage {
            get {
                return ResourceManager.GetString("CurrentImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion du contenu de la section publique.
        /// </summary>
        internal static string gestionSectionPublique {
            get {
                return ResourceManager.GetString("gestionSectionPublique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion de l&apos;utilisateur.
        /// </summary>
        internal static string gestionUtilisateur {
            get {
                return ResourceManager.GetString("gestionUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voir les écoles.
        /// </summary>
        internal static string getEcolesSecteur {
            get {
                return ResourceManager.GetString("getEcolesSecteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voir les utilisateurs.
        /// </summary>
        internal static string getUtilsSecteur {
            get {
                return ResourceManager.GetString("getUtilsSecteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des écoles.
        /// </summary>
        internal static string lstEcoles {
            get {
                return ResourceManager.GetString("lstEcoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des secteurs.
        /// </summary>
        internal static string lstSecteurs {
            get {
                return ResourceManager.GetString("lstSecteurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des utilisateurs.
        /// </summary>
        internal static string lstUtils {
            get {
                return ResourceManager.GetString("lstUtils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion du calendrier.
        /// </summary>
        internal static string menuCalendrier {
            get {
                return ResourceManager.GetString("menuCalendrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des écoles.
        /// </summary>
        internal static string menuEcoles {
            get {
                return ResourceManager.GetString("menuEcoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion de la section publique.
        /// </summary>
        internal static string menuPublique {
            get {
                return ResourceManager.GetString("menuPublique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des secteurs.
        /// </summary>
        internal static string menuSecteurs {
            get {
                return ResourceManager.GetString("menuSecteurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des utilisateurs.
        /// </summary>
        internal static string menuUtil {
            get {
                return ResourceManager.GetString("menuUtil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier une nouvelle.
        /// </summary>
        internal static string modifierNouvelle {
            get {
                return ResourceManager.GetString("modifierNouvelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier/Supprimer une nouvelle.
        /// </summary>
        internal static string modifierSupprimerNouvelle {
            get {
                return ResourceManager.GetString("modifierSupprimerNouvelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher des utilisateurs.
        /// </summary>
        internal static string RechUtils {
            get {
                return ResourceManager.GetString("RechUtils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur, Nom, Prénom.
        /// </summary>
        internal static string RechUtilsParam {
            get {
                return ResourceManager.GetString("RechUtilsParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Section publique.
        /// </summary>
        internal static string sectionPublique {
            get {
                return ResourceManager.GetString("sectionPublique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toutes les écoles.
        /// </summary>
        internal static string tousEcoles {
            get {
                return ResourceManager.GetString("tousEcoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tous les secteurs.
        /// </summary>
        internal static string tousSecteurs {
            get {
                return ResourceManager.GetString("tousSecteurs", resourceCulture);
            }
        }
    }
}
