//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34003
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez le projet Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;avez pas accès à cette section..
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le contenu du message ne peut être vide..
        /// </summary>
        internal static string contenuObligatoire {
            get {
                return ResourceManager.GetString("contenuObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La description ne peut être vide..
        /// </summary>
        internal static string descriptionVide {
            get {
                return ResourceManager.GetString("descriptionVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La liste des destinataires ne peut être vide..
        /// </summary>
        internal static string destObligatoire {
            get {
                return ResourceManager.GetString("destObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;école a été ajoutée au secteur..
        /// </summary>
        internal static string EcoleAjoutSectOk {
            get {
                return ResourceManager.GetString("EcoleAjoutSectOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le courriel ne correspond pas..
        /// </summary>
        internal static string EmailMatch {
            get {
                return ResourceManager.GetString("EmailMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite..
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ {0} est obligatoire..
        /// </summary>
        internal static string fieldRequired {
            get {
                return ResourceManager.GetString("fieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ {0} doit comprendre au moins {2} caractères..
        /// </summary>
        internal static string fieldStringLength {
            get {
                return ResourceManager.GetString("fieldStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fil de discussion a bien été ajouté..
        /// </summary>
        internal static string filAjoute {
            get {
                return ResourceManager.GetString("filAjoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier est trop gros, la taille maximum est de : .
        /// </summary>
        internal static string FileTooLarge {
            get {
                return ResourceManager.GetString("FileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les images doivent être de type : .
        /// </summary>
        internal static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fil de discussion a bien été supprimé..
        /// </summary>
        internal static string filSupprime {
            get {
                return ResourceManager.GetString("filSupprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le message bien été envoyé..
        /// </summary>
        internal static string messageEnvoye {
            get {
                return ResourceManager.GetString("messageEnvoye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le message n&apos;a pu être envoyé, une erreur est survenue..
        /// </summary>
        internal static string messagePasEnvoye {
            get {
                return ResourceManager.GetString("messagePasEnvoye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les messages ont bien été supprimés..
        /// </summary>
        internal static string messagesSupprimes {
            get {
                return ResourceManager.GetString("messagesSupprimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le message a bien été supprimé..
        /// </summary>
        internal static string messageSupprime {
            get {
                return ResourceManager.GetString("messageSupprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vos informations personnelles ont été mises à jour..
        /// </summary>
        internal static string ModifierInfosOK {
            get {
                return ResourceManager.GetString("ModifierInfosOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nouveau mot de passe et la confirmation ne correspondent pas..
        /// </summary>
        internal static string NewPasswordMatch {
            get {
                return ResourceManager.GetString("NewPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce champ ne peut pas être modifié..
        /// </summary>
        internal static string nonEditable {
            get {
                return ResourceManager.GetString("nonEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La nouvelle a bien été ajoutée..
        /// </summary>
        internal static string nouvelleAjoutee {
            get {
                return ResourceManager.GetString("nouvelleAjoutee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La nouvelle a bien été modifiée..
        /// </summary>
        internal static string nouvelleModifiee {
            get {
                return ResourceManager.GetString("nouvelleModifiee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La nouvelle n&apos;a pu être ajoutée..
        /// </summary>
        internal static string nouvellePasAjoutee {
            get {
                return ResourceManager.GetString("nouvellePasAjoutee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La nouvelle a bien été supprimée..
        /// </summary>
        internal static string nouvelleSupprimee {
            get {
                return ResourceManager.GetString("nouvelleSupprimee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre mot de passe n&apos;a pas été changé..
        /// </summary>
        internal static string PasswordChangeNotOK {
            get {
                return ResourceManager.GetString("PasswordChangeNotOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre mot de passe a été changé..
        /// </summary>
        internal static string PasswordChangeOK {
            get {
                return ResourceManager.GetString("PasswordChangeOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mot de passe est invalide..
        /// </summary>
        internal static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un courriel vous a été envoyé pour confirmer la réinitialisation de votre mot de passe..
        /// </summary>
        internal static string PasswordResetConfirm {
            get {
                return ResourceManager.GetString("PasswordResetConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La pièce jointe dépasse la taille limite qui est de {0} MB..
        /// </summary>
        internal static string pieceTropLourde {
            get {
                return ResourceManager.GetString("pieceTropLourde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre mot de passe a bien été réinitialisé..
        /// </summary>
        internal static string ResetPasswordOK {
            get {
                return ResourceManager.GetString("ResetPasswordOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre mot de passe n&apos;a pas été réinitialisé..
        /// </summary>
        internal static string ResetPasswortInvalid {
            get {
                return ResourceManager.GetString("ResetPasswortInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nouveau secteur a été ajouté..
        /// </summary>
        internal static string SectAjoutOk {
            get {
                return ResourceManager.GetString("SectAjoutOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce secteur n&apos;existe pas..
        /// </summary>
        internal static string SectInexistant {
            get {
                return ResourceManager.GetString("SectInexistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le secteur a été modifié..
        /// </summary>
        internal static string SectModifOk {
            get {
                return ResourceManager.GetString("SectModifOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune école pour ce secteur..
        /// </summary>
        internal static string SectNoSchool {
            get {
                return ResourceManager.GetString("SectNoSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun utilisateur pour ce secteur..
        /// </summary>
        internal static string SectNoUser {
            get {
                return ResourceManager.GetString("SectNoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le sujet du message ne peut être vide..
        /// </summary>
        internal static string sujetObligatoire {
            get {
                return ResourceManager.GetString("sujetObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le titre ne peut être vide..
        /// </summary>
        internal static string titreVide {
            get {
                return ResourceManager.GetString("titreVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;avez pas accès à cette section car vous n&apos;êtes inscrit à aucun secteur..
        /// </summary>
        internal static string UserAccessDenied {
            get {
                return ResourceManager.GetString("UserAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;utilisateur a été ajouté au secteur..
        /// </summary>
        internal static string UserAjoutSectOk {
            get {
                return ResourceManager.GetString("UserAjoutSectOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom d&apos;usager est invalide..
        /// </summary>
        internal static string UsernameInvalid {
            get {
                return ResourceManager.GetString("UsernameInvalid", resourceCulture);
            }
        }
    }
}
