//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez le projet Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Partenaire {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Partenaire() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Partenaire", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un partenaire.
        /// </summary>
        internal static string ajouterPartenaire {
            get {
                return ResourceManager.GetString("ajouterPartenaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajout d&apos;un partenaire.
        /// </summary>
        internal static string ajoutPartenaire {
            get {
                return ResourceManager.GetString("ajoutPartenaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment supprimer &quot;{0}&quot;?.
        /// </summary>
        internal static string confirmerSupprPartenaire {
            get {
                return ResourceManager.GetString("confirmerSupprPartenaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier/Supprimer un partenaire.
        /// </summary>
        internal static string modifierSupprimerPartenaire {
            get {
                return ResourceManager.GetString("modifierSupprimerPartenaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier un partenaire.
        /// </summary>
        internal static string modifPartenaire {
            get {
                return ResourceManager.GetString("modifPartenaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le partenaire a bien été ajouté..
        /// </summary>
        internal static string partenaireAjoute {
            get {
                return ResourceManager.GetString("partenaireAjoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite lors de l&apos;ajout du partenaire..
        /// </summary>
        internal static string partenaireErreur {
            get {
                return ResourceManager.GetString("partenaireErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le partenaire spécifié est inexistant..
        /// </summary>
        internal static string partenaireInexistant {
            get {
                return ResourceManager.GetString("partenaireInexistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le partenaire a bien été mis à jour..
        /// </summary>
        internal static string partenaireModifie {
            get {
                return ResourceManager.GetString("partenaireModifie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le partenaire a bien été supprimé..
        /// </summary>
        internal static string partenaireSupprime {
            get {
                return ResourceManager.GetString("partenaireSupprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression d&apos;un partenaire.
        /// </summary>
        internal static string suppressionPartenaire {
            get {
                return ResourceManager.GetString("suppressionPartenaire", resourceCulture);
            }
        }
    }
}
