//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez le projet Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Publication {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Publication() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Publication", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une publication.
        /// </summary>
        internal static string ajouterPublication {
            get {
                return ResourceManager.GetString("ajouterPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publication d&apos;un document.
        /// </summary>
        internal static string ajoutPublication {
            get {
                return ResourceManager.GetString("ajoutPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun résultat.
        /// </summary>
        internal static string aucunResultat {
            get {
                return ResourceManager.GetString("aucunResultat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier est requis.
        /// </summary>
        internal static string fichierRequis {
            get {
                return ResourceManager.GetString("fichierRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La publication spécifiée est invalide ou inexistante..
        /// </summary>
        internal static string idPublicationInvalide {
            get {
                return ResourceManager.GetString("idPublicationInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mot clé(s).
        /// </summary>
        internal static string motClesPlaceholder {
            get {
                return ResourceManager.GetString("motClesPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La publication a bien été ajoutée..
        /// </summary>
        internal static string publicationAjoutee {
            get {
                return ResourceManager.GetString("publicationAjoutee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite lors de l&apos;ajout de la publication..
        /// </summary>
        internal static string publicationErreur {
            get {
                return ResourceManager.GetString("publicationErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier publié est inaccessible..
        /// </summary>
        internal static string publicationErreurFichier {
            get {
                return ResourceManager.GetString("publicationErreurFichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La publication a bien été supprimée..
        /// </summary>
        internal static string publicationSupprimee {
            get {
                return ResourceManager.GetString("publicationSupprimee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recherche par sujet.
        /// </summary>
        internal static string rechercheCategorie {
            get {
                return ResourceManager.GetString("rechercheCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recherche par mot clé.
        /// </summary>
        internal static string rechercheMotCle {
            get {
                return ResourceManager.GetString("rechercheMotCle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression d&apos;une publication.
        /// </summary>
        internal static string suppressionPublication {
            get {
                return ResourceManager.GetString("suppressionPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer une publication.
        /// </summary>
        internal static string supprimerPublication {
            get {
                return ResourceManager.GetString("supprimerPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tous.
        /// </summary>
        internal static string tous {
            get {
                return ResourceManager.GetString("tous", resourceCulture);
            }
        }
    }
}
