//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34003
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez le projet Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sectoriel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sectoriel() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Sectoriel", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Boîte de réception.
        /// </summary>
        internal static string boiteReception {
            get {
                return ResourceManager.GetString("boiteReception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation du nouveau compte.
        /// </summary>
        internal static string ConfirmAccount {
            get {
                return ResourceManager.GetString("ConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer.
        /// </summary>
        internal static string ConfirmResetPassword {
            get {
                return ResourceManager.GetString("ConfirmResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contenu du message....
        /// </summary>
        internal static string contenuPlaceholder {
            get {
                return ResourceManager.GetString("contenuPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Corbeille.
        /// </summary>
        internal static string corbeille {
            get {
                return ResourceManager.GetString("corbeille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dernier Message.
        /// </summary>
        internal static string dernierMessage {
            get {
                return ResourceManager.GetString("dernierMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        internal static string descriptionPlaceholder {
            get {
                return ResourceManager.GetString("descriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;utilisateur {0} n&apos;existe pas..
        /// </summary>
        internal static string destinataireInexistant {
            get {
                return ResourceManager.GetString("destinataireInexistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Noms d&apos;utilisateur.
        /// </summary>
        internal static string destinatairesPlaceholder {
            get {
                return ResourceManager.GetString("destinatairesPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoyé a.
        /// </summary>
        internal static string envoyeA {
            get {
                return ResourceManager.GetString("envoyeA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoyer.
        /// </summary>
        internal static string envoyer {
            get {
                return ResourceManager.GetString("envoyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fil de Discussion.
        /// </summary>
        internal static string filDiscussion {
            get {
                return ResourceManager.GetString("filDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forum.
        /// </summary>
        internal static string forum {
            get {
                return ResourceManager.GetString("forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Messagerie.
        /// </summary>
        internal static string messagerie {
            get {
                return ResourceManager.GetString("messagerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Messages envoyés.
        /// </summary>
        internal static string messagesEnvoyes {
            get {
                return ResourceManager.GetString("messagesEnvoyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier vos informations personnelles.
        /// </summary>
        internal static string ModifierInfos {
            get {
                return ResourceManager.GetString("ModifierInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier votre mot de passe.
        /// </summary>
        internal static string ModifierMDP {
            get {
                return ResourceManager.GetString("ModifierMDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier un message du forum.
        /// </summary>
        internal static string modifierMessageForum {
            get {
                return ResourceManager.GetString("modifierMessageForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour {0}, &lt;br/&gt; Pour compléter votre adhésion au Portail pédagogique, cliquez sur le lien suivant : .
        /// </summary>
        internal static string msgConfirmAccount {
            get {
                return ResourceManager.GetString("msgConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour {0}, &lt;br /&gt; Pour compléter le processus de réinitialisation de votre mot de passe, cliquez sur ce lien : .
        /// </summary>
        internal static string msgReset {
            get {
                return ResourceManager.GetString("msgReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb Lectures.
        /// </summary>
        internal static string nbLectures {
            get {
                return ResourceManager.GetString("nbLectures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb Messages.
        /// </summary>
        internal static string nbMessage {
            get {
                return ResourceManager.GetString("nbMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        internal static string nom {
            get {
                return ResourceManager.GetString("nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau.
        /// </summary>
        internal static string nouveau {
            get {
                return ResourceManager.GetString("nouveau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau fil de discussion.
        /// </summary>
        internal static string nouveauFil {
            get {
                return ResourceManager.GetString("nouveauFil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau Message.
        /// </summary>
        internal static string nouveauMessage {
            get {
                return ResourceManager.GetString("nouveauMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répondre.
        /// </summary>
        internal static string repondre {
            get {
                return ResourceManager.GetString("repondre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répondre à un fil de discussion.
        /// </summary>
        internal static string repondreFil {
            get {
                return ResourceManager.GetString("repondreFil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répondre à un message.
        /// </summary>
        internal static string repondreMessage {
            get {
                return ResourceManager.GetString("repondreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réinitialiser.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélection des destinataires (par nom/prénom).
        /// </summary>
        internal static string selectionDestinataires {
            get {
                return ResourceManager.GetString("selectionDestinataires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réinitialisation de votre mot de passe.
        /// </summary>
        internal static string subjectReset {
            get {
                return ResourceManager.GetString("subjectReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sujet.
        /// </summary>
        internal static string sujetPlaceholder {
            get {
                return ResourceManager.GetString("sujetPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        internal static string supprimer {
            get {
                return ResourceManager.GetString("supprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Titre.
        /// </summary>
        internal static string titrePlaceholder {
            get {
                return ResourceManager.GetString("titrePlaceholder", resourceCulture);
            }
        }
    }
}
