//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez le projet Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sondages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sondages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Sondages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un sondage.
        /// </summary>
        internal static string ajouterSondage {
            get {
                return ResourceManager.GetString("ajouterSondage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajout d&apos;un sondage.
        /// </summary>
        internal static string ajoutSondage {
            get {
                return ResourceManager.GetString("ajoutSondage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun résultat disponible.
        /// </summary>
        internal static string aucunResultat {
            get {
                return ResourceManager.GetString("aucunResultat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun sondage disponible.
        /// </summary>
        internal static string aucunSondage {
            get {
                return ResourceManager.GetString("aucunSondage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez sélectionner un choix valide..
        /// </summary>
        internal static string choixInvalide {
            get {
                return ResourceManager.GetString("choixInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date de fin doit être supérieure à la date de début.
        /// </summary>
        internal static string dateFinAvantDebut {
            get {
                return ResourceManager.GetString("dateFinAvantDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date doit avoir le format &quot;AAAA/MM/JJ&quot;.
        /// </summary>
        internal static string dateInvalide {
            get {
                return ResourceManager.GetString("dateInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date doit être égale ou supérieure à aujourd&apos;hui.
        /// </summary>
        internal static string datePassee {
            get {
                return ResourceManager.GetString("datePassee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fin le.
        /// </summary>
        internal static string finLe {
            get {
                return ResourceManager.GetString("finLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le sondage spécifié est invalide ou inexistant..
        /// </summary>
        internal static string idSondageInvalide {
            get {
                return ResourceManager.GetString("idSondageInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Résultats des sondages.
        /// </summary>
        internal static string resultatsSondages {
            get {
                return ResourceManager.GetString("resultatsSondages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le sondage a bien été ajouté..
        /// </summary>
        internal static string sondageAjoute {
            get {
                return ResourceManager.GetString("sondageAjoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite lors de l&apos;ajout du sondage..
        /// </summary>
        internal static string sondageErreur {
            get {
                return ResourceManager.GetString("sondageErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le sondage sélectionné est invalide, ou vous avez déjà voté sur celui-ci..
        /// </summary>
        internal static string sondageInvalide {
            get {
                return ResourceManager.GetString("sondageInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sondages en cours.
        /// </summary>
        internal static string sondagesEnCours {
            get {
                return ResourceManager.GetString("sondagesEnCours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le sondage a bien été supprimé..
        /// </summary>
        internal static string sondageSupprime {
            get {
                return ResourceManager.GetString("sondageSupprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression d&apos;un sondage.
        /// </summary>
        internal static string suppressionSondage {
            get {
                return ResourceManager.GetString("suppressionSondage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un sondage.
        /// </summary>
        internal static string supprimerSondage {
            get {
                return ResourceManager.GetString("supprimerSondage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à vote.
        /// </summary>
        internal static string vote {
            get {
                return ResourceManager.GetString("vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à votes.
        /// </summary>
        internal static string votes {
            get {
                return ResourceManager.GetString("votes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre vote a été enregistré avec succès..
        /// </summary>
        internal static string voteSucces {
            get {
                return ResourceManager.GetString("voteSucces", resourceCulture);
            }
        }
    }
}
